spring:
  application:
    name: CinemaApp
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    validate-on-migrate: true
  mail:
    host: pro.turbo-smtp.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: false
<<<<<<< HEAD
      
=======

>>>>>>> af9dc51 (Update README)
mail:
  from: ${MAIL_FROM}

frontend:
  url: ${FRONTEND_URL}

server:
  port: ${SERVER_PORT}
  ssl:
    enabled: true
    key-store: file:.cert/keystore.p12
    key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD}
    key-store-type: PKCS12

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration: 900000
  refresh-token:
    expiration: 604800000

cookie:
  secure: true
  http-only: true
  same-site: None
